import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Layers, Target, BookOpen, GraduationCap, LockKeyhole } from 'lucide-react';
import { toast } from 'sonner';
import { useApp, useLoad } from '../hooks/useApp';
import { api } from '../services/api';
import { Button, Field, ErrorState, Loading, Avatar } from '../components/ui';
import ThemeToggle from '../components/ThemeToggle';
export function AuthPage() {
  const { setUser, error: connectionError } = useApp(); const [signup, setSignup] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setBusy(true); setError(''); const body = Object.fromEntries(new FormData(e.currentTarget)); try { const d = await api(signup ? '/auth/signup' : '/auth/login', { method: 'POST', body }); setUser(d.user); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <div className="auth-page"><div className="auth-story"><div className="brand"><img src="/favicon.svg" alt=""/>recall.</div><div><span className="eyebrow">A SPACE FOR YOUR CURIOSITY</span><h1>Learn a little.<br/>Remember<br/>a lot.</h1><p>Collect what matters. Make it memorable.<br/>Learn better, together.</p><div className="auth-benefits"><span><Check size={17}/> Your notes, beautifully organized</span><span><Check size={17}/> Study at your own pace</span><span><Check size={17}/> Share a little knowledge</span></div></div><span>One card at a time.</span></div><div className="auth-form"><ThemeToggle className="auth-theme-toggle"/><div><h2>{signup ? 'Make yourself at home.' : 'Welcome back.'}</h2><p>{signup ? 'Your next chapter starts with a flashcard.' : 'Your learning space is right where you left it.'}</p>{connectionError && <ErrorState message={connectionError}/>}<form className="form-stack" onSubmit={submit}>{signup ? <><Field label="Full name"><input required name="name" maxLength={60} autoComplete="name" placeholder="Gaurav Prakash"/></Field><Field label="Unique username" hint="3–24 letters, numbers, or underscores."><input required name="username" pattern="[a-zA-Z0-9_]{3,24}" autoComplete="username" placeholder="your_username"/></Field><Field label="Email"><input required type="email" name="email" autoComplete="email" placeholder="you@example.com"/></Field></> : <Field label="Username or email"><input required name="identifier" autoComplete="username" placeholder="Your username or email"/></Field>}<Field label="Password" hint={signup ? 'Use at least 10 characters.' : undefined}><input required type="password" name="password" minLength={signup ? 10 : 1} maxLength={128} autoComplete={signup ? 'new-password' : 'current-password'} placeholder="Enter your password"/></Field>{error && <ErrorState message={error}/>}<Button type="submit" className="primary" loading={busy}>{signup ? 'Create your account' : 'Sign in'}<ArrowRight size={17}/></Button></form><p className="auth-switch">{signup ? 'Already have an account?' : 'New to Recall?'} <button className="text-button" onClick={() => { setSignup(!signup); setError(''); }}>{signup ? 'Sign in' : 'Create an account'}</button></p></div></div></div>;
}
export function SettingsPage() {
  const { user, setUser, refresh } = useApp(); const [form, setForm] = useState({ name: user.name, bio: user.bio || '', dailyGoal: user.dailyGoal || 20 }), [busy, setBusy] = useState(false), [error, setError] = useState('');
  return <><div className="page-heading"><div><div className="eyebrow">MAKE YOURSELF AT HOME</div><h1>Your settings</h1><p>A learning space that feels like you.</p></div></div><div className="settings-panel"><div className="profile-header"><Avatar user={user}/><div><h2>{user.name}</h2><p>@{user.username}</p></div></div><form className="form-stack" onSubmit={async e => { e.preventDefault(); setBusy(true); try { const d = await api('/auth/profile', { method: 'PATCH', body: form }); setUser(d.user); refresh(); toast.success('Settings saved'); } catch (e) { setError(e.message); } finally { setBusy(false); } }}><Field label="Display name"><input required maxLength={60} value={form.name} onChange={e => setForm(f => ({ ...f, name: e.target.value }))}/></Field><Field label="About you"><textarea maxLength={300} rows={3} value={form.bio} onChange={e => setForm(f => ({ ...f, bio: e.target.value }))}/></Field><Field label="Daily review goal" hint="Choose a goal that fits your day. You can change it anytime."><select value={form.dailyGoal} onChange={e => setForm(f => ({ ...f, dailyGoal: Number(e.target.value) }))}>{[5, 10, 20, 30, 50, 100].map(n => <option key={n} value={n}>{n} cards a day</option>)}</select></Field><div className="sharing-note"><LockKeyhole size={17}/> Your email and study progress are private.</div>{error && <ErrorState message={error}/>}<Button className="primary" loading={busy} type="submit">Save changes <Check size={16}/></Button></form></div></>;
}
export function ProgressPage() {
  const { revision } = useApp(); const { data, loading, error } = useLoad(() => api('/stats'), [revision]);
  if (loading) return <Loading/>; if (error) return <ErrorState message={error}/>; const s = data.stats;
  return <><div className="page-heading"><div><div className="eyebrow">EVERY REVIEW COUNTS</div><h1>Look how far you’re going.</h1><p>Build your knowledge, one small session at a time.</p></div></div><div className="stats-grid">{[[Layers, 'Cards in your library', s.totalCards], [BookOpen, 'Reviews completed', s.reviewed], [Target, 'Ready to review', s.due], [GraduationCap, 'Long-term cards', s.mastered]].map(([Icon, label, value]) => <div className="stat-card" key={label}><span><Icon size={22}/></span><strong>{value}</strong><p>{label}</p></div>)}</div><div className="progress-panel"><div><span className="eyebrow">TODAY’S MOMENTUM</span><h2>{s.reviewsToday >= s.goal ? 'Daily goal, done.' : 'A little time for a lasting habit.'}</h2><p>{s.reviewsToday} of {s.goal} cards reviewed today. Daily totals reset at midnight UTC.</p><div className="goal-progress"><span style={{ width: `${Math.min(100, s.reviewsToday / s.goal * 100)}%` }}/></div><Link to="/" className="button primary">Back to your library <ArrowRight size={17}/></Link></div><div className="progress-insight"><h3>Give your memory some space.</h3><p>Cards rated “Again” return sooner. Cards you know well are spaced further apart. Long-term cards have a review interval of at least 21 days.</p></div></div></>;
}
