import { useState, useEffect, useCallback } from 'react';
import { Link, useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Plus, Play, Share2, LockKeyhole, Globe2, Search, Pencil, Trash2, Bookmark, Copy, History, RotateCcw, ArrowRight, Layers, Radio } from 'lucide-react';
import { toast } from 'sonner';
import { api, imageUrl } from '../services/api';
import { useApp, useLoad } from '../hooks/useApp';
import { useFolderRealtime } from '../hooks/useRealtime';
import { Button, Loading, ErrorState, Empty, FolderIcon, Avatar, Tag, Menu, Modal } from '../components/ui';
import CardEditor from '../components/CardEditor';
import ShareModal from '../components/ShareModal';
import FolderModal from '../components/FolderModal';
const describe = type => ({ 'card.created': 'added a card', 'card.updated': 'edited a card', 'card.deleted': 'deleted a card', 'folder.updated': 'updated this folder', 'folder.members.changed': 'changed sharing', 'folder.archived': 'archived this folder' })[type] || type.replaceAll('.', ' ');
export default function FolderPage() {
  const { id } = useParams(); const { revision, refresh, user } = useApp(); const navigate = useNavigate();
  const [tick, setTick] = useState(0), [query, setQuery] = useState(''), [tag, setTag] = useState('all'), [flipped, setFlipped] = useState({}), [editor, setEditor] = useState(null), [share, setShare] = useState(false), [editFolder, setEditFolder] = useState(false), [remove, setRemove] = useState(null), [activity, setActivity] = useState(false), [bookmarkFilter, setBookmarkFilter] = useState(false), [liveVersions, setLiveVersions] = useState({});
  const { data, error, loading } = useLoad(() => Promise.all([api(`/folders/${id}`), api(`/folders/${id}/cards`)]).then(([f, c]) => ({ ...f, ...c })), [id, revision, tick]);
  // Live layer: committed events arrive over the socket; polling only runs as a fallback while disconnected.
  const { presence, connected, setEditing } = useFolderRealtime(id, {
    onEvent: e => { setTick(v => v + 1); if (e.type === 'card.updated' && e.version != null) setLiveVersions(v => ({ ...v, [e.aggregateId]: e.version })); if (e.actor?.id !== user?.id) toast(`${e.actor?.name || 'Someone'} ${describe(e.type)}`, { description: e.detail?.slice(0, 80), icon: <Radio size={15}/> }); },
    onRevoked: () => { toast.error('Your access to this folder was removed.'); navigate('/'); }
  });
  useEffect(() => { if (connected) return; const timer = setInterval(() => { if (!document.hidden && !editor) setTick(v => v + 1); }, 15000); return () => clearInterval(timer); }, [editor, connected]);
  if (!data) return error ? <ErrorState message={error}/> : <Loading/>;
  const { folder, cards } = data; const canEdit = ['owner', 'editor'].includes(folder.role);
  const others = presence.filter(p => p.user.id !== user?.id); const editingBy = Object.fromEntries(others.filter(p => p.editing).map(p => [p.editing, p]));
  const tags = [...new Set(cards.flatMap(c => c.tags))]; const filtered = cards.filter(c => (tag === 'all' || c.tags.includes(tag)) && (!bookmarkFilter || c.progress?.bookmarked) && `${c.front.text} ${c.back.text} ${c.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const due = cards.filter(c => !c.progress?.dueAt || new Date(c.progress.dueAt) <= new Date()).length;
  async function bookmark(card) { try { await api(`/cards/${card.id}/bookmark`, { method: 'PATCH', body: { bookmarked: !card.progress?.bookmarked } }); refresh(); } catch (e) { toast.error(e.message); } }
  return <><Link to="/" className="back-link"><ArrowLeft size={16}/> Back to library</Link>{error && <ErrorState message={error}/>}<div className="folder-page-heading"><div className={`large-folder-icon ${folder.color}`}><FolderIcon name={folder.icon} size={34}/></div><div><div className="folder-heading-meta"><span>{folder.visibility === 'global' ? <Globe2 size={13}/> : <LockKeyhole size={13}/>} {folder.visibility === 'global' ? 'Global collection' : 'Private collection'}</span>{folder.role === 'editor' && <span>Editor access</span>}</div><h1>{folder.title}</h1><p>{folder.description}</p></div><div className="folder-heading-actions"><Button className="secondary" onClick={() => setShare(true)}><Share2 size={16}/> Share</Button>{canEdit && <Button className="primary" onClick={() => setEditor({})}><Plus size={18}/> Add card</Button>}</div></div>
    <div className="folder-info-bar"><div><Avatar user={folder.owner} small/><span>Created by <Link to={`/u/${folder.owner?.username}`}><strong>@{folder.owner?.username}</strong></Link></span><span className="divider"/><span>{cards.length} cards</span><span className="divider"/><span>{due} due for review</span>{folder.originalCreator && <span>Copied from @{folder.originalCreator}</span>}</div><div>{connected && <div className="presence-stack" title={others.length ? `Here now: ${others.map(p => p.user.name).join(', ')}` : 'You are the only one here'}>{others.slice(0, 4).map(p => <span className="presence-avatar" key={p.user.id} style={{ '--peer': p.color }}><Avatar user={p.user} small/></span>)}<span className="presence-label"><Radio size={12}/> {others.length ? `${others.length} here` : 'Live'}</span></div>}<button className="text-button" onClick={() => setActivity(true)}><History size={15}/> Activity</button><Menu items={[folder.role === 'owner' && { label: 'Edit folder', icon: <Pencil size={15}/>, action: () => setEditFolder(true) }, { label: folder.saved ? 'Unsave folder' : 'Save to library', icon: <Bookmark size={15}/>, action: async () => { try { await api(`/folders/${id}/save`, { method: 'PATCH', body: { saved: !folder.saved } }); refresh(); toast.success(folder.saved ? 'Removed from saved' : 'Saved to your library'); } catch (e) { toast.error(e.message); } } }, { label: 'Make a private copy', icon: <Copy size={15}/>, action: async () => { try { const d = await api(`/folders/${id}/copy`, { method: 'POST' }); refresh(); navigate(`/folders/${d.folder.id}`); } catch (e) { toast.error(e.message); } } }]}/></div></div>
    {cards.length > 0 && <div className="folder-study-strip"><div><span className="study-strip-icon"><Layers size={25}/></span><div><h3>A little practice makes it stick.</h3><p>Flip a few cards, or settle into a focused study session.</p></div></div><div><Button className="secondary" onClick={() => navigate(`/folders/${id}/study?mode=all`)}>Quick review</Button><Button className="primary" disabled={!due} onClick={() => navigate(`/folders/${id}/study?mode=due`)}><Play size={16}/> Study due cards <span className="button-count">{due}</span></Button></div></div>}
    <div className="cards-toolbar"><h2>Flashcards <span>{cards.length}</span></h2><div><div className="folder-search"><Search size={16}/><input aria-label="Search flashcards" placeholder="Search cards or tags" value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Filter by tag" value={tag} onChange={e => setTag(e.target.value)}><option value="all">All tags</option>{tags.map(t => <option key={t}>{t}</option>)}</select><button className={`icon-button border-button ${bookmarkFilter ? 'selected' : ''}`} aria-label="Show bookmarked cards" aria-pressed={bookmarkFilter} onClick={() => setBookmarkFilter(v => !v)}><Bookmark size={18}/></button></div></div>
    {!filtered.length ? <Empty title={cards.length ? 'No cards match your filters' : 'Your first card starts here'} text={cards.length ? 'Try another keyword or tag.' : 'Add a question on the front and a memorable answer on the back.'} action={canEdit && !cards.length && <Button className="primary" onClick={() => setEditor({})}><Plus size={17}/> Create your first card</Button>}/> : <div className="flashcard-grid">{filtered.map((c, i) => { const side = flipped[c.id] ? c.back : c.front; return <article className={`flashcard-item ${flipped[c.id] ? 'is-flipped' : ''}`} key={c.id}><div className="flashcard-top"><span>{String(i + 1).padStart(2, '0')} <span> / {flipped[c.id] ? 'ANSWER' : 'QUESTION'}</span></span><div>{editingBy[c.id] && <span className="editing-badge" style={{ '--peer': editingBy[c.id].color }} title={`${editingBy[c.id].user.name} is editing this card`}><Pencil size={11}/> {editingBy[c.id].user.name.split(' ')[0]}</span>}<button aria-label={c.progress?.bookmarked ? 'Remove bookmark' : 'Bookmark card'} className={`icon-button ${c.progress?.bookmarked ? 'selected' : ''}`} onClick={() => bookmark(c)}><Bookmark size={16} fill={c.progress?.bookmarked ? 'currentColor' : 'none'}/></button>{canEdit && <Menu label={`Options for card ${i + 1}`} items={[{ label: 'Edit card', icon: <Pencil size={15}/>, action: () => setEditor(c) }, { label: 'Delete card', icon: <Trash2 size={15}/>, danger: true, action: () => setRemove(c) }]}/>}</div></div><button className="card-content" aria-label={`Flip card ${i + 1}`} onClick={() => setFlipped(f => ({ ...f, [c.id]: !f[c.id] }))}>{side.image && <img src={imageUrl(side.image)} alt={side.text || 'Flashcard image'}/>}<p>{side.text}</p></button><div className="flashcard-footer"><div>{c.tags.slice(0, 2).map(t => <Tag key={t}>{t}</Tag>)}</div><button className="text-button" onClick={() => setFlipped(f => ({ ...f, [c.id]: !f[c.id] }))}><RotateCcw size={13}/> Flip</button></div></article>; })}{canEdit && <button className="add-card-tile" onClick={() => setEditor({})}><span><Plus size={24}/></span><strong>Add a flashcard</strong><p>One more thing worth remembering.</p></button>}</div>}
    {editor && <CardEditor folder={folder} card={editor.id ? editor : null} onClose={() => setEditor(null)} onEditing={setEditing} liveVersion={editor.id ? liveVersions[editor.id] : null}/>} {share && <ShareModal folder={folder} onClose={() => setShare(false)}/>} {editFolder && <FolderModal folder={folder} onClose={() => setEditFolder(false)}/>} {activity && <ActivityModal id={id} onClose={() => setActivity(false)}/>}
    <Modal open={!!remove} onClose={() => setRemove(null)} title="Delete this flashcard?" description="This removes the card and its version history. This action cannot be undone."><div className="modal-actions"><Button className="secondary" onClick={() => setRemove(null)}>Keep card</Button><Button className="danger-button" onClick={async () => { try { await api(`/cards/${remove.id}`, { method: 'DELETE' }); setRemove(null); refresh(); toast.success('Card deleted'); } catch (e) { toast.error(e.message); } }}>Delete card</Button></div></Modal>
  </>;
}
function ActivityModal({ id, onClose }) { const { data, loading, error } = useLoad(() => api(`/folders/${id}/activity`), [id]); return <Modal open onClose={onClose} title="Folder activity" description="Recent changes by people in this folder.">{loading ? <Loading/> : error ? <ErrorState message={error}/> : !data.activity.length ? <Empty title="A fresh start" text="Changes to this collection will appear here."/> : <div className="activity-list">{data.activity.map(a => <div key={a.id}><Avatar user={a.actor} small/><div><strong>{a.actor?.name} <span>{a.action.replaceAll('.', ' ')}</span></strong><p>{a.detail}</p><small>{new Date(a.createdAt).toLocaleString()}</small></div></div>)}</div>}</Modal>; }
