import { Router } from 'express';
import multer from 'multer';
import { rateLimit } from 'express-rate-limit';
import { z } from 'zod';
import * as auth from '../controllers/authController.js';
import * as folders from '../controllers/folderController.js';
import * as cards from '../controllers/cardController.js';
import * as study from '../controllers/studyController.js';
import * as social from '../controllers/socialController.js';
import * as projects from '../controllers/projectController.js';
import { requireAuth } from '../middleware/auth.js';
import { validate, signupSchema, folderSchema, cardSchema, usernameSchema, idSchema, projectSchema } from '../middleware/validate.js';
import { asyncHandler as a } from '../utils/errors.js';
const r = Router(); const authLimit = rateLimit({ windowMs: 15 * 60000, limit: 30, standardHeaders: 'draft-8', legacyHeaders: false });
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 1 } });
r.post('/auth/signup', authLimit, validate(signupSchema), a(auth.signup));
r.post('/auth/login', authLimit, validate(z.object({ identifier: z.string().min(1).max(254), password: z.string().min(1).max(128) })), a(auth.login));
r.post('/auth/logout', a(auth.logout)); r.get('/auth/me', a(auth.me));
r.get('/users', a(auth.searchPeople));
r.get('/users/:username', a(auth.publicProfile));
r.post('/users/:username/follow', requireAuth, a(social.follow));
r.delete('/users/:username/follow', requireAuth, a(social.unfollow));
r.post('/users/:username/connect', requireAuth, a(social.connect));
r.post('/users/:username/connect/accept', requireAuth, a(social.accept));
r.post('/users/:username/connect/decline', requireAuth, a(social.decline));
r.delete('/users/:username/connect', requireAuth, a(social.unfriend));
r.get('/me/friends', requireAuth, a(social.friends));
r.get('/me/requests', requireAuth, a(social.requests));
r.get('/projects', requireAuth, a(projects.list));
r.post('/projects', requireAuth, validate(projectSchema), a(projects.create));
r.get('/projects/:id', a(projects.get));
r.patch('/projects/:id', requireAuth, validate(projectSchema.extend({ version: z.number().int().min(0) })), a(projects.update));
r.patch('/projects/:id/archive', requireAuth, validate(z.object({ archived: z.boolean() })), a(projects.archive));
r.post('/projects/:id/folders', requireAuth, validate(z.object({ folderId: idSchema })), a(projects.addFolder));
r.delete('/projects/:id/folders/:folderId', requireAuth, a(projects.removeFolder));
r.patch('/auth/profile', requireAuth, validate(z.object({ name: z.string().trim().min(1).max(60), bio: z.string().max(300), dailyGoal: z.number().int().min(1).max(200), desiredRetention: z.number().min(0.7).max(0.97).optional() })), a(auth.profile));
r.get('/folders', (req, res, next) => req.query.scope === 'explore' ? next() : requireAuth(req, res, next), a(folders.list));
r.get('/folders/archived', requireAuth, a(folders.archived));
r.post('/folders', requireAuth, validate(folderSchema), a(folders.create));
r.get('/folders/:id', a(folders.get));
r.patch('/folders/:id', requireAuth, validate(folderSchema.extend({ version: z.number().int().min(0) })), a(folders.update));
r.post('/folders/:id/members', requireAuth, validate(z.object({ username: usernameSchema, role: z.enum(['viewer', 'editor', 'remove']) })), a(folders.member));
r.post('/folders/:id/copy', requireAuth, a(folders.copy));
r.patch('/folders/:id/archive', requireAuth, validate(z.object({ archived: z.boolean() })), a(folders.archive));
r.patch('/folders/:id/save', requireAuth, validate(z.object({ saved: z.boolean() })), a(folders.save));
r.get('/folders/:id/activity', a(folders.activity));
r.get('/folders/:id/cards', a(cards.list)); r.post('/folders/:id/cards', requireAuth, validate(cardSchema), a(cards.create));
r.post('/folders/:id/images', requireAuth, rateLimit({ windowMs: 60000, limit: 20 }), upload.single('image'), a(cards.upload));
const importUpload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 25 * 1024 * 1024, files: 1 } });
r.post('/folders/:id/import', requireAuth, rateLimit({ windowMs: 60000, limit: 10 }), importUpload.single('file'), a(cards.importFile));
r.get('/folders/:id/export', requireAuth, a(cards.exportFile));
r.patch('/cards/:id', requireAuth, validate(cardSchema.extend({ version: z.number().int().min(0) })), a(cards.update));
r.delete('/cards/:id', requireAuth, a(cards.remove)); r.get('/cards/:id/revisions', requireAuth, a(cards.revisions));
r.patch('/cards/:id/bookmark', requireAuth, validate(z.object({ bookmarked: z.boolean() })), a(cards.bookmark));
r.get('/media/:id', a(cards.image));
r.post('/reviews', requireAuth, validate(z.object({ cardId: idSchema, rating: z.enum(['again', 'hard', 'good', 'easy']), requestId: z.uuid(), version: z.number().int().min(0) })), a(study.review));
r.get('/stats', requireAuth, a(study.stats));
export default r;
