/** Public collections seeded for the demo account. Visible on the logged-out homepage. */
export const demoLibrary = [
  { title: 'System design', description: 'The building blocks behind systems that scale.', color: 'violet', icon: 'layers', cards: [
    ['What is the difference between horizontal and vertical scaling?', 'Horizontal scaling adds more machines. Vertical scaling adds resources to one machine. Horizontal scaling needs coordination but can improve resilience.', ['scalability']],
    ['What does idempotency mean?', 'Repeating the same request has the same intended effect as executing it once. An idempotency key lets a server recognize retries.', ['apis']],
    ['When would you use optimistic concurrency control?', 'When conflicts are rare. Send a version with each write and reject it if the stored version changed since the read.', ['concurrency']],
    ['What is the purpose of a database index?', 'An index finds matching records without scanning every row. It uses extra storage and adds work to writes.', ['databases']],
    ['What is the transactional outbox pattern?', 'Write a domain change and its event in the same database transaction. A worker publishes committed events; consumers deduplicate retries.', ['distributed-systems']],
    ['Why can at-least-once delivery create duplicates?', 'An acknowledgement can be lost after processing. The producer retries because it cannot tell whether the consumer succeeded.', ['queues']],
  ] },
  { title: 'JavaScript essentials', description: 'Small details that make everyday code more reliable.', color: 'orange', icon: 'code', cards: [
    ['What is a closure in JavaScript?', 'A function plus access to its lexical environment, even after the outer function has returned.', ['javascript']],
    ['What is the difference between === and ==?', '=== compares without type coercion. == may convert types before comparing.', ['basics']],
    ['How does Promise.all handle rejection?', 'It rejects as soon as any input promise rejects. The other operations are not cancelled automatically.', ['async']],
    ['What does the event loop do?', 'It runs queued tasks when the call stack is clear. Promise callbacks are microtasks and run before the next task.', ['async']],
    ['What is a pure function?', 'It returns the same result for the same inputs and has no observable side effects.', ['functions']],
    ['What does `this` refer to in an arrow function?', 'The `this` value from the enclosing lexical scope. Arrow functions do not get their own `this`.', ['javascript']],
  ] },
  { title: 'Design fundamentals', description: 'Principles for interfaces that feel effortless.', color: 'pink', icon: 'palette', cards: [
    ['What is visual hierarchy?', 'Arranging elements so importance is clear, using size, contrast, spacing, and position.', ['ui']],
    ['What is progressive disclosure?', 'Show essential options first and reveal more detail when needed, reducing initial cognitive load.', ['ux']],
    ['Why does accessible contrast matter?', 'It helps people distinguish text and controls, including people with low vision or a bright screen.', ['accessibility']],
    ['What is a design token?', 'A named value for a reusable design decision such as color, spacing, typography, or radius.', ['systems']],
    ['What is Fitts’s law in UI design?', 'The time to reach a target grows with distance and shrinks with target size. Make frequent actions large and nearby.', ['ux']],
    ['What is the purpose of whitespace?', 'Empty space groups related items, reduces noise, and gives the eye a place to rest.', ['layout']],
  ] },
  { title: 'Learning how to learn', description: 'Make study time go further with memory science.', color: 'green', icon: 'brain', cards: [
    ['What is active recall?', 'Trying to retrieve information from memory before looking at the answer.', ['memory']],
    ['What is spaced repetition?', 'Reviewing information at increasing intervals, adapted to how well you remember it.', ['memory']],
    ['What is interleaving?', 'Mixing related topics or problem types during practice instead of blocking one type at a time.', ['practice']],
    ['What is desirable difficulty?', 'A challenge that slows performance now but improves long-term learning, such as testing yourself.', ['practice']],
    ['What is the testing effect?', 'Practice tests strengthen memory more than extra re-reading of the same material.', ['memory']],
    ['Why does sleep matter for memory?', 'Sleep consolidates recent learning. Cramming overnight trades short-term performance for weaker long-term recall.', ['habits']],
  ] },
  { title: 'Database concepts', description: 'Queries, transactions, and how data stays consistent.', color: 'slate', icon: 'terminal', cards: [
    ['What does ACID stand for?', 'Atomicity, Consistency, Isolation, and Durability.', ['transactions']],
    ['What does a unique index guarantee?', 'No two documents can share the same indexed value (or combination), subject to the index options.', ['indexes']],
    ['What is a replica set?', 'A group of nodes that keep copies of the same data. A primary accepts writes; secondaries replicate them.', ['replication']],
    ['What is a covering index?', 'An index that contains every field a query needs, so the database can answer without reading the full document.', ['indexes']],
    ['What is eventual consistency?', 'Replicas may be briefly out of date, then converge. Readers can see stale data until replication catches up.', ['distributed-systems']],
    ['When is denormalization useful?', 'When a read path is hot and joining data on every request is too expensive. You trade write complexity for faster reads.', ['modeling']],
  ] },
  { title: 'React fundamentals', description: 'How React thinks about UI, state, and updates.', color: 'blue', icon: 'code', cards: [
    ['What is a React component?', 'A function (or class) that returns UI from props and state. React re-renders it when those inputs change.', ['react']],
    ['What does useState do?', 'It stores a value that survives re-renders and triggers a re-render when you set a new value.', ['hooks']],
    ['When should you use useEffect?', 'To synchronize with something outside React: subscriptions, timers, or reading from the DOM after paint.', ['hooks']],
    ['What is a key in a list?', 'A stable identity so React can match items across renders instead of remounting the whole list.', ['react']],
    ['What is lifting state up?', 'Moving shared state to the closest common parent so siblings stay in sync through props.', ['state']],
    ['Why is mutating state directly a bug?', 'React compares the new state reference to decide whether to re-render. In-place mutation can hide the change.', ['state']],
  ] },
  { title: 'Computer networks', description: 'How packets find their way across the internet.', color: 'violet', icon: 'globe', cards: [
    ['What does TCP guarantee that UDP does not?', 'Reliable, ordered delivery with retransmission. UDP is datagram-oriented and leaves reliability to the application.', ['tcp']],
    ['What is DNS?', 'A distributed lookup that maps names like example.com to IP addresses (and other records).', ['dns']],
    ['What is a TLS handshake for?', 'It authenticates the server (usually) and agrees on keys so later traffic is encrypted and integrity-protected.', ['tls']],
    ['What is the difference between HTTP and HTTPS?', 'HTTPS is HTTP over TLS. The content of the request and response is encrypted in transit.', ['http']],
    ['What does a CDN cache?', 'Copies of static (and sometimes dynamic) responses near users, so origin servers do less work and latency drops.', ['http']],
    ['What is CORS?', 'A browser rule: a page on origin A may only read responses from origin B if B explicitly allows it via headers.', ['http']],
  ] },
  { title: 'Operating systems', description: 'Processes, memory, and what the kernel actually does.', color: 'orange', icon: 'terminal', cards: [
    ['What is the difference between a process and a thread?', 'A process has its own address space. Threads in a process share that space and can run concurrently.', ['concurrency']],
    ['What is a context switch?', 'The OS saves one thread’s CPU state and restores another’s so many programs can share a core.', ['scheduling']],
    ['What is virtual memory?', 'Each process sees its own address space. The OS maps pages to physical RAM or to disk (swap) as needed.', ['memory']],
    ['What is a deadlock?', 'A cycle of waits: each holder needs a resource another holder will not release. None can make progress.', ['concurrency']],
    ['What does a mutex protect?', 'A critical section so only one thread at a time mutates shared data.', ['concurrency']],
    ['What is a page fault?', 'The CPU accessed a virtual page that is not currently mapped in RAM. The OS must load it or raise an error.', ['memory']],
  ] },
  { title: 'Git and GitHub', description: 'Version control habits that keep teams unblocked.', color: 'green', icon: 'book', cards: [
    ['What does `git commit` record?', 'A snapshot of the staged changes plus a message, parent commit(s), and author metadata.', ['git']],
    ['What is the difference between merge and rebase?', 'Merge creates a join commit. Rebase replays your commits on top of another tip, rewriting history.', ['git']],
    ['What is a pull request?', 'A request to review and merge a branch. CI, comments, and required checks usually run against it.', ['github']],
    ['When should you use `git stash`?', 'To temporarily shelve uncommitted work so you can switch branches or pull without committing half-done changes.', ['git']],
    ['What is a fast-forward merge?', 'The target branch pointer simply moves forward because the incoming history is a straight-line descendant.', ['git']],
    ['Why is rewriting published history risky?', 'Other people may have based work on those commits. Force-pushing can drop or duplicate their changes.', ['git']],
  ] },
  { title: 'CSS and layout', description: 'How modern pages actually sit on the screen.', color: 'pink', icon: 'palette', cards: [
    ['What is the CSS box model?', 'Content, padding, border, and margin. `box-sizing: border-box` includes padding and border in the stated width.', ['css']],
    ['When is Flexbox a better fit than Grid?', 'Flexbox is for one-dimensional alignment (a row or a column). Grid is for two-dimensional layouts.', ['layout']],
    ['What does `position: sticky` do?', 'The element scrolls with its container until it hits a threshold, then stays pinned.', ['css']],
    ['What is a stacking context?', 'A local z-index world. `opacity`, `transform`, and `position` can create one so children cannot escape it.', ['css']],
    ['What is the difference between `em` and `rem`?', '`em` is relative to the parent font size. `rem` is relative to the root (`html`) font size.', ['css']],
    ['Why use `min-width: 0` on a flex child?', 'Flex items default to `min-width: auto` and may refuse to shrink below their content. Zero lets them overflow-wrap.', ['layout']],
  ] },
  { title: 'SQL essentials', description: 'Select, join, and group data without surprises.', color: 'blue', icon: 'terminal', cards: [
    ['What does `WHERE` filter versus `HAVING`?', '`WHERE` filters rows before grouping. `HAVING` filters groups after `GROUP BY`.', ['sql']],
    ['What is an INNER JOIN?', 'Rows that have a match in both tables. Unmatched rows from either side are dropped.', ['joins']],
    ['What is a LEFT JOIN?', 'All rows from the left table, plus matching right-table columns or NULL when there is no match.', ['joins']],
    ['What does `GROUP BY` do?', 'It collapses rows that share the same grouping keys and lets you compute aggregates like COUNT or SUM.', ['sql']],
    ['What is a primary key?', 'A column (or set of columns) that uniquely identifies each row and cannot be NULL.', ['modeling']],
    ['What is a transaction isolation level?', 'A rule for what concurrent transactions can see: dirty reads, non-repeatable reads, and phantoms.', ['transactions']],
  ] },
  { title: 'Data structures', description: 'Pick the right shape for the problem.', color: 'slate', icon: 'layers', cards: [
    ['When is a hash map the right choice?', 'When you need average O(1) insert, lookup, and delete by key and do not need sorted order.', ['maps']],
    ['What is the difference between an array and a linked list?', 'Arrays are contiguous and index in O(1). Linked lists splice in O(1) given a node but scan to find an index.', ['lists']],
    ['What does a stack give you?', 'Last-in, first-out. Useful for undo, DFS, and matching brackets.', ['stacks']],
    ['What is a binary search tree?', 'Each node’s left subtree holds smaller keys and the right holds larger ones, so search can skip half the tree.', ['trees']],
    ['What is a heap good for?', 'Repeatedly taking the min or max in O(log n). Priority queues are usually heaps.', ['heaps']],
    ['What is a graph versus a tree?', 'A tree is an acyclic connected graph with one path between any pair. A graph may have cycles and many components.', ['graphs']],
  ] },
  { title: 'Python basics', description: 'The everyday language of scripts, data, and interviews.', color: 'green', icon: 'flask', cards: [
    ['What is a list comprehension?', 'A compact expression that builds a list: `[x * 2 for x in items if x > 0]`.', ['python']],
    ['What is the difference between a list and a tuple?', 'Lists are mutable. Tuples are immutable and can be dictionary keys if their contents are hashable.', ['python']],
    ['What does `*args` collect?', 'Extra positional arguments as a tuple. `**kwargs` collects extra keyword arguments as a dict.', ['functions']],
    ['What is a generator?', 'A function that `yield`s values lazily. It keeps local state between iterations and does not build the full list.', ['python']],
    ['What does `is` compare versus `==`?', '`is` tests object identity (same object in memory). `==` tests value equality and can be overloaded.', ['python']],
    ['What is a virtual environment for?', 'An isolated set of packages for one project so dependencies do not collide with other projects or the system Python.', ['tooling']],
  ] },
  { title: 'HTTP and REST', description: 'Status codes, verbs, and APIs that behave.', color: 'violet', icon: 'globe', cards: [
    ['What does HTTP 201 mean?', 'Created. The request succeeded and a new resource exists, often with a Location header.', ['http']],
    ['When should you return 409 Conflict?', 'When the request is well-formed but clashes with current state, such as a stale version number.', ['http']],
    ['What is the difference between PUT and PATCH?', 'PUT replaces the resource with the payload. PATCH applies a partial update.', ['rest']],
    ['Why are GET requests supposed to be safe?', 'They must not change server state. Caches, crawlers, and retries assume GET can be repeated freely.', ['rest']],
    ['What is an idempotency key used for?', 'Clients send a unique key with a mutating request so a retry does not create a second charge or record.', ['apis']],
    ['What does 429 Too Many Requests mean?', 'The client hit a rate limit. Back off, often using a Retry-After header.', ['http']],
  ] },
  { title: 'Interview behavioral', description: 'Stories you can tell without rambling.', color: 'orange', icon: 'book', cards: [
    ['What is the STAR format?', 'Situation, Task, Action, Result. A short structure that keeps behavioral answers concrete.', ['interviews']],
    ['How do you talk about a conflict with a teammate?', 'Describe the disagreement, what you did to understand their view, the decision you reached, and the outcome.', ['interviews']],
    ['What belongs in a “tell me about yourself” answer?', 'A 60–90 second arc: relevant past, what you do now, and why this role is the next step.', ['interviews']],
    ['How should you answer “What is your weakness?”', 'Name a real gap, show how you work on it, and keep it job-relevant without disqualifying yourself.', ['interviews']],
    ['What makes a good “failed project” story?', 'Own the mistake, show what you changed afterward, and end on a later success that used that lesson.', ['interviews']],
    ['How do you quantify impact?', 'Prefer numbers: time saved, error rate dropped, revenue, users, or latency. Approximate if you must, and say so.', ['interviews']],
  ] },
];
