import { Link, useNavigate } from 'react-router-dom';
import { LockKeyhole, Globe2, Copy, Share2, Pencil, Archive, ArrowUpRight, Layers, Users } from 'lucide-react';
import { Avatar, FolderIcon, Menu, Tag } from './ui';
import { api } from '../services/api';
import { useApp } from '../hooks/useApp';
import { toast } from 'sonner';
export default function FolderTile({ folder, onShare, onEdit, onArchive, list }) {
  const { refresh } = useApp(); const navigate = useNavigate(); const f = folder;
  const items = [f.role === 'owner' && { label: 'Edit folder', icon: <Pencil size={15}/>, action: () => onEdit(f) }, { label: 'Share folder', icon: <Share2 size={15}/>, action: () => onShare(f) }, { label: 'Make a private copy', icon: <Copy size={15}/>, action: async () => { try { const d = await api(`/folders/${f.id}/copy`, { method: 'POST' }); refresh(); navigate(`/folders/${d.folder.id}`); toast.success('Private copy created'); } catch (e) { toast.error(e.message); } } }, f.role === 'owner' && { label: 'Archive folder', icon: <Archive size={15}/>, action: () => onArchive(f) }];
  return <article className={`folder-tile ${list ? 'list-tile' : ''}`}><div className={`tile-cover ${f.color}`}><Link to={`/folders/${f.id}`} className="cover-link" aria-label={`Open ${f.title}`}><span className="folder-icon"><FolderIcon name={f.icon} size={30}/></span><span className="cover-word">{f.icon === 'code' ? '{ }' : f.icon === 'globe' ? 'Hola.' : f.icon === 'palette' ? 'Aa' : f.icon === 'terminal' ? '>_' : f.icon === 'brain' ? 'Think.' : 'Learn.'}</span></Link><span className="visibility-badge">{f.visibility === 'global' ? <Globe2 size={12}/> : <LockKeyhole size={12}/>} {f.visibility === 'global' ? 'Global' : 'Private'}</span><div className="tile-menu"><Menu items={items} label={`Options for ${f.title}`}/></div></div><div className="tile-body"><Link to={`/folders/${f.id}`} className="tile-title">{f.title}<ArrowUpRight size={17}/></Link><p>{f.description || 'A new collection of things worth remembering.'}</p><div className="tile-tags">{(f.tags || [f.icon === 'layers' ? 'learning' : f.icon, f.role === 'viewer' ? 'community' : 'personal']).slice(0, 2).map(t => <Tag key={t}>{t}</Tag>)}</div><div className="tile-footer"><span><Layers size={14}/>{f.cardCount} cards</span><div className="tile-people"><Avatar user={f.owner} small/>{f.members?.slice(0, 2).map(m => <Avatar key={m.user.id} user={m.user} small/>)}{f.memberCount > 1 && <span>{f.memberCount} learners</span>}</div></div></div></article>;
}
